services:
  bot:
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - "${DATA_PATH}:/app/data"
    env_file:
      - .env
    environment:
      - TZ=Europe/Samara
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    networks:
      - ulstu-bots-network
      - internal
    
  db:
    image: postgres:latest
    restart: always
    ports:
      - "5431:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    env_file:
      - .env
    volumes:
      - ./data/database:/var/lib/postgresql/data
    networks:
      - internal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  pg_admin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    env_file:
      - .env
    ports:
      - "80:80"
    networks:
      - internal
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy

networks:
  internal:
    driver: bridge
  ulstu-bots-network:
    external: true